### PR TITLE
Forked over and cloned repo, moved project into the new folder, all t…

### PR DESCRIPTION
**Pull request by mbrow234**
…he test seem to still be behaving as intended. Initial commit.

### CODE REVIEW

**Comment by mbrow234** [comment]
Don will you ensure me that this is on track? Thanks

**Comment by donbstringham** [comment]
You are on the right path!  A couple of comments, though.  On the User object I would remove the EMPTY_STRING constant and place it in another object that already exists (hint).  Use the value objects already created to build the properties in the User object, as well.

**Comment by mbrow234** [comment]
Don I redid a portion of the application. I for some reason wasn't thinking about the interface. I implemented it on the User and have changed the test a bit, just added in some more. I don't know if I need to write those test again for the owner and admin, but I will leave them as is, since we haven't implemented those objects yet anyways. Please look at the latest commit for feedback. Thanks.

**Comment by donbstringham** [comment]
How is it that you know what to do but the other students struggle?  Am I that vague?  Anyways, good job +1 full-credit.  You got it!  There are a few enhancements I would make but we can talk on Tuesday about it.

**Comment by mbrow234** [comment]
I wrote down everything we discussed in class. I posted on that discussion
board the reqs earlier today

**Pull request closed without merging**
